name: CI/CD Pipeline

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          cd porfolio
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure this file is in your repo

      - name: Build Docker image
        run: |
          cd porfolio
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio:latest

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: SSH into GCP VM and Deploy Docker Container
        env:
          VM_IP: ${{ secrets.VM_HOST }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
            gcloud compute ssh "${{ secrets.VM_USER }}@instance-20241011-150157" --project=${{ secrets.PROJECT_ID }} --zone=${{ secrets.GCP_VM_ZONE }} --command "
              docker pull $DOCKER_USERNAME/portfolio:latest &&
              docker stop portfolio || true &&
              docker rm portfolio || true &&
              docker run -d -p 5000:5000 --name portfolio $DOCKER_USERNAME/portfolio:latest
            " --tunnel-through-iap --ssh-key-file=$HOME/.ssh/id_rsa
