name: CI/CD Pipeline

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }} 
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          cd portfolio  # Ensure this is the correct directory
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/portfolio:latest .

      - name: Push Docker image to GCR
        run: |
          cd portfolio  # Ensure this is the correct directory
          docker push gcr.io/${{ secrets.PROJECT_ID }}/portfolio:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy portfolio \  # Replace with your actual service name
            --image gcr.io/${{ secrets.PROJECT_ID }}/portfolio:latest \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated \
            --port 5000
